runtime: nodejs22
service: avisti-conecta

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

entrypoint: node dist/app-avisti-connect/server/server.mjs

env_variables:
  NODE_ENV: 'production'
  NG_ALLOWED_HOSTS: '*.appspot.com'